
# Can be provided by environment variable. for example:
# CAMEL_COMPONENT_JMS_USERNAME=
camel.component.jms.username=artemis
camel.component.jms.password=artemis

camel.component.jms.lazyCreateTransactionManager=false
camel.component.jms.cacheLevelName=CACHE_CONSUMER
camel.component.jms.transacted=true
