DROP TABLE IF EXISTS public.minio_events_journal;

CREATE TABLE IF NOT EXISTS public.minio_events_journal
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_time timestamp with time zone NOT NULL,
    status_time timestamp with time zone,
    retry_time timestamp with time zone,
    retry_num integer DEFAULT 0,
    event_data jsonb,
    status character varying COLLATE pg_catalog."default" DEFAULT 'NEW'::character varying,
    bucket_name character varying COLLATE pg_catalog."default",
    object_key character varying COLLATE pg_catalog."default",
    queue_name character varying COLLATE pg_catalog."default",
    error_message character varying COLLATE pg_catalog."default"
)
