apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: joke
    app.kubernetes.io/runtime: camel
  name: joke
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: joke
  type: ClusterIP
