quarkus.datasource.camel.db-kind=postgresql
quarkus.datasource.camel.username=postgres
quarkus.datasource.camel.password=postgres
quarkus.datasource.camel.jdbc.url=jdbc:postgresql://oravm05:5432/postgres
quarkus.datasource.camel.jdbc.max-size=16
