camel.main.shutdownTimeout=5
camel.main.name=splitattachments
camel.main.basePackageScan=org.example.project.split


camel.route-template[0].template-id=mailTemplate
camel.route-template[0].username=tom
camel.route-template[0].password=tom
camel.route-template[0].delay=10000

camel.route-template[1].template-id=mailTemplate
camel.route-template[1].username=jeff
camel.route-template[1].password=jeff
camel.route-template[1].delay=15000
