

camel.kamelet.jms-ibm-mq-source.serverName = oravm05
camel.kamelet.jms-ibm-mq-source.serverPort = 1414
camel.kamelet.jms-ibm-mq-source.queueManager = QM1
camel.kamelet.jms-ibm-mq-source.channel = DEV.APP.SVRCONN
camel.kamelet.jms-ibm-mq-source.username = app
camel.kamelet.jms-ibm-mq-source.password = passw0rd
#camel.kamelet.jms-ibm-mq-source.sslCipherSuite=*TLS12