camel.component.aws2-s3.access-key=JT7FuXClyVJ1tM1PT3lb
camel.component.aws2-s3.secret-key=BPkH4ixqOwK7KTo7DLmyL8zVjdnVewnR66zxLdHY
camel.component.aws2-s3.uri-endpoint-override=http://oravm05:9000
camel.component.aws2-s3.override-endpoint=true
camel.component.aws2-s3.region=us-east-1
camel.component.aws2-s3.force-path-style=true
camel.component.aws2-s3.operation=getObject


camel.component.jms.transacted=true

camel.kamelet.jms-apache-artemis-sink.brokerURL=tcp://oravm05:61616?user=artemis&password=artemis
