camel.component.jms.username=artemis
camel.component.jms.password=artemis
camel.component.jms.transacted=true


camel.component.jms.lazyCreateTransactionManager=false
camel.component.jms.cacheLevelName=CACHE_CONSUMER

