

camel.kamelet.jms-ibm-mq-sink.serverName = oravm05
camel.kamelet.jms-ibm-mq-sink.serverPort = 1414
camel.kamelet.jms-ibm-mq-sink.queueManager = QM1
camel.kamelet.jms-ibm-mq-sink.channel = DEV.APP.SVRCONN
camel.kamelet.jms-ibm-mq-sink.username = app
camel.kamelet.jms-ibm-mq-sink.password = passw0rd
#camel.kamelet.jms-ibm-mq-sink.sslCipherSuite=*TLS12

#camel.kamelet.jms-apache-artemis-source.password=artemis

# camel.component.jms.username=artemis
# camel.component.jms.password=artemis
# camel.component.jms.transacted=true


#camel.component.jms.lazyCreateTransactionManager=false
#camel.component.jms.cacheLevelName=CACHE_CONSUMER

